import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./Component/Navbar";
import About from "./Component/About";
import Footer from "./Component/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <nav className="w-10/12 mx-auto">
          <Navbar></Navbar>
        </nav>
        <div className="min-h-[calc(100vh-100px)]">
        {children}
        </div>
        <Footer></Footer>
      </body>
    </html>
  );
}
